/*
 * ¿Preparad@ para aprender o repasar el lenguaje de programación que tú quieras?
 * - Recuerda que todas las instrucciones de participación están en el
 *   repositorio de GitHub.
 *
 * Lo primero... ¿Ya has elegido un lenguaje?
 * - No todos son iguales, pero sus fundamentos suelen ser comunes.
 * - Este primer reto te servirá para familiarizarte con la forma de participar
 *   enviando tus propias soluciones.
 *
 * EJERCICIO:
 * - Crea un comentario en el código y coloca la URL del sitio web oficial del
 *   lenguaje de programación que has seleccionado.
 * - Representa las diferentes sintaxis que existen de crear comentarios
 *   en el lenguaje (en una línea, varias...).
 * - Crea una variable (y una constante si el lenguaje lo soporta).
 * - Crea variables representando todos los tipos de datos primitivos
 *   del lenguaje (cadenas de texto, enteros, booleanos...).
 * - Imprime por terminal el texto: "¡Hola, [y el nombre de tu lenguaje]!"
 *
 * ¿Fácil? No te preocupes, recuerda que esta es una ruta de estudio y
 * debemos comenzar por el principio.
 */

//! como tal javascript no tiene una pagina oficial, pero te coloco 
//! la de node.js : https://nodejs.org/en

// esto es un comentario de una sola linea
/*
esto es un comentario de varias lineas o bloque
*/

// declaracion de una variable y una constante
let nombre = 'myNombre';
const edad = 20;

// tipos de datos
let apellido; // String
let  edad2 = 20; // Number
let  casado = false; // Boolean
let  hijos = null; // Null
let  direccion = undefined; // Undefined
let altura = 1.75; // float y/o double
let BigInt = 1234567890123456789012345678901234567890n; // BigInt

console.log("Hola, JavaScript!");


